# Generated by Django 4.1.5 on 2023-02-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
