# Generated by Django 4.0.9 on 2023-02-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ("-created",)},
        ),
        migrations.RenameField(
            model_name="review",
            old_name="payload",
            new_name="content",
        ),
    ]
