# Generated by Django 4.1.5 on 2023-02-07 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("direct_messages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="chattingroom",
            name="users",
            field=models.ManyToManyField(
                related_name="chatting_rooms", to="users.user"
            ),
        ),
    ]
